# Generated by Django 5.1.1 on 2024-10-05 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clientes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Nome")),
                (
                    "birth",
                    models.DateField(blank=True, verbose_name="Data de nascimento"),
                ),
                ("addr", models.JSONField(verbose_name="Endereço")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("picture", models.ImageField(upload_to="uploads/pic/")),
                (
                    "added",
                    models.DateTimeField(auto_now=True, verbose_name="Adicionado"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
        ),
        migrations.CreateModel(
            name="Planos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Nome")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Valor"
                    ),
                ),
                ("desc", models.TextField(verbose_name="Descrição")),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "added",
                    models.DateTimeField(auto_now=True, verbose_name="Adicionado"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fichas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("desc", models.TextField(verbose_name="Observações")),
                ("file", models.FileField(upload_to="uploads/fichas/")),
                (
                    "added",
                    models.DateTimeField(auto_now=True, verbose_name="Adicionado"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clientes.clientes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contratos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateField(verbose_name="Início")),
                ("end", models.DateField(verbose_name="Fim")),
                ("file", models.FileField(upload_to="uploads/contracts/")),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "added",
                    models.DateTimeField(auto_now=True, verbose_name="Adicionado"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clientes.clientes",
                    ),
                ),
                (
                    "plano",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clientes.planos",
                    ),
                ),
            ],
        ),
    ]
