# Generated by Django 5.1.1 on 2024-10-05 16:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Clientes",
            new_name="Cliente",
        ),
        migrations.RenameModel(
            old_name="Contratos",
            new_name="Contrato",
        ),
        migrations.RenameModel(
            old_name="Fichas",
            new_name="Ficha",
        ),
        migrations.RenameModel(
            old_name="Planos",
            new_name="Plano",
        ),
    ]
